server:
  port: 8081
spring:
  application:
    name: hello-service
  cloud:
    loadbalancer:
      retry:
        enabled: true
eureka:
  client:
    service-url:
       defaultZone: http://localhost:1111/eureka/
